Eslint  and formating enhancement
zadam/trilium pull request #3827
Opened 2023-04-10 16:56 UTC by soulsands

Hi zadam. this pr is about eslint and formating staff, and I shared a vscode setting.
Highly recommand using vscode for javascript development. 
You can check the file .eslintrc.js for eslint config. Currently I turn off all the rules that throw exceptions.you can turn them on one by one to see the influence and decide to leave them on or off.  
These tools really helps a lot, please check it.

2023-04-14 17:01 UTC, zadam requested changes
I appreciate the effort on this!

2023-04-14 17:01 UTC, zadam commented on .eslintrc.js
> +    plugins: ['prettier'],
The immediate problem is that I have significant work in branches and reformatting would introduce many conflicts. We can merge in the config etc., but it shouldn't be run automatically before 0.60 is released.

2023-04-14 17:01 UTC, zadam commented on .eslintignore
> +spec-es6
`spec` and `spec-es6` don't have to be excluded IMHO

2023-04-14 17:01 UTC, zadam commented on .husky/pre-commit
> +npx lint-staged
Similar to prettier. For now I'd like to avoid automatic changes. We can prepare this, but before 0.60, it should not run automatically. Maybe just comment out for now.

2023-04-14 17:02 UTC, zadam commented
> Highly recommand using vscode for javascript development.

Only people who didn't try IntelliJ / WebStorm can recommend VSCode ;-)

2023-04-15 01:52 UTC, soulsands commented
> > Highly recommand using vscode for javascript development.
> 
> Only people who didn't try IntelliJ / WebStorm can recommend VSCode ;-)

yeah I shouldn't mention that. that was a hasty advice haha. I have'nt tried webstorm in recent years though.

Anyway I just hope people can code in this project easily, getting rid of lint and style stuffs, saving enegy for necessary works.

By the way, when will the next version be released? I can't wait for it.

2023-04-16 21:25 UTC, zadam commented
> By the way, when will the next version be released? I can't wait for it.

Still several weeks. 0.60 changes a lot of things for the https://github.com/zadam/trilium/issues/3682

2023-04-17 03:55 UTC, soulsands commented
Not sure if this request is appropriate, but would you consider releasing a patch version. The patch would include a number of fixes and performance enhancements. I'm working on Windows and haven't successfully packaged the server yet. Of course, if it takes too much time, please feel free to disregard it. @zadam

2023-04-17 18:44 UTC, merged

2023-04-18 03:50 UTC, soulsands commented
> @soulsands not sure what you mean exactly. I will release 0.59.4 shortly and will keep releasing patch versions until 0.60 stable is released.

 My bad, I thought the next version would be 0.60, my english expression has flaws.

2023-04-18 05:27 UTC, soulsands commented
@zadam  Hi, I tried 0.59.4 and found it doesn't include my commits. I'm wondering if it was missed or intentionallyfor the next release. Personally I'm waiting for the persistent cache one actually, which would improve the browser-using experience a lot in poor network.

2023-04-18 20:50 UTC, zadam commented
The patch releases contain only small scale fixes. Your changes will be in 0.60, but it will take some time.

2023-04-19 01:59 UTC, soulsands commented
Thanks for you explaining patiently, I understand know